http_server_host = "0.0.0.0"
log_level = "INFO"
avail_path = "/var/lib/avail-light/avail_path"
log_format_json = true

operation_mode='client'
query_parallelism = 1
query_timeout = 15
replication_factor = 2
max_negotiating_inbound_streams = 10000
task_command_buffer_size = 30000
per_connection_event_buffer_size = 10000
<<<<<<< HEAD
bootstrap_period = 120
=======
bootstrap_period = 120
block_processing_delay = 0
>>>>>>> ad48ae98aaecb6c489fca5c9b3cf00ea4fb1b86a
