http_server_host = "0.0.0.0"
log_level = "INFO"
avail_path = "/var/lib/avail-light/avail_path"
log_format_json = true

operation_mode='client'
query_parallelism = 3
query_timeout = 15
replication_factor = 5