---

- name: Remove any existing versions
  shell: rm /usr/local/bin/avail* /opt/avail* || true
  ignore_errors: true
  
- name: Download avail-light binary
  block:
    - name: Download avail-light archive on x86_64 architecture
      register: avail_download_results
      ansible.builtin.get_url:
        url: https://github.com/availproject/avail-light/releases/download/{{ client_version }}/avail-light-linux-amd64.tar.gz
        dest: /opt/avail_light_{{ client_version }}_linux_amd.tar.gz
        mode: 0600
        force: false
        timeout: 300
      when: ansible_architecture == "x86_64"
    - name: Download avail-light archive on aarch64 architecture
      register: avail_download_results
      ansible.builtin.get_url:
        url: https://github.com/availproject/avail-light/releases/download/{{ client_version }}/avail-light-linux-arm64.tar.gz #arm64 or aarch64
        dest: /opt/avail_light_{{ client_version }}_linux_aarch64.tar.gz
        mode: 0600
        force: false
        timeout: 300
      when: ansible_architecture == "aarch64"

- name: Extract avail-light archive
  block:
    - name: Extract avail-light archive on x86_64 architecture
      ansible.builtin.unarchive:
        src: /opt/avail_light_{{ client_version }}_linux_amd.tar.gz
        dest: /opt
        remote_src: true
      when: ansible_architecture == "x86_64"
    - name: Extract avail-light archive on aarch64 architecture
      ansible.builtin.unarchive:
        src: /opt/avail_light_{{ client_version }}_linux_aarch64.tar.gz
        dest: /opt
        remote_src: true
      when: ansible_architecture == "aarch64"

- name: Create a symbolic link for avail-light
  block:
    - name: Create a symbolic link on x86_64 architecture
      ansible.builtin.file:
        src: /opt/avail-light-linux-amd64
        dest: /usr/local/bin/{{ service_prefix }}-{{ client_version }}
        state: link
      when: ansible_architecture == "x86_64"
    - name: Create a symbolic link on aarch64 architecture
      ansible.builtin.file:
        src: /opt/avail-light-linux-arm64 #arm64 or aarch64
        dest: /usr/local/bin/{{ service_prefix }}-{{ client_version }}
        state: link
      when: ansible_architecture == "aarch64"