  
- name: Create config file for {{ client_role }}
  ansible.builtin.template:
    src: client-config.yml
    dest: "/etc/avail-light/config.yml"
    owner: "{{ avail_user }}"
    group: "{{ avail_user }}"
    mode: 0755
  notify: 
    - Restart all services
    - Restart DD Agent
    
- name: Generate service file for {{ node_count }} {{ client_role }} nodes
  ansible.builtin.template:
    src: avail-light.service
    dest: "/etc/systemd/system/avail-light-{{ item }}.service"
    owner: "{{ avail_user }}"
    group: "{{ avail_user }}"
    mode: 0755
  loop: "{{ range(1, node_count + 1) | list }}"
  notify: 
    - Restart all services
    - Restart DD Agent