  
- name: Create config file for {{ client_role }}
  ansible.builtin.template:
    src: client-config.yml
    dest: "/etc/avail-light/config.yml"
    owner: "{{ avail_user }}"
    group: "{{ avail_user }}"
    mode: 0755
  notify: 
    - Restart all services
    - Restart DD Agent
    
- name: Generate service file for {{ node_count }} {{ client_role }} nodes
  ansible.builtin.template:
    src: avail-light.service
    dest: "/etc/systemd/system/avail-light-{{ item }}.service"
    owner: "{{ avail_user }}"
    group: "{{ avail_user }}"
    mode: 0755
  loop: "{{ range(1, node_count + 1) | list }}"
  notify: 
    - Restart all services
    - Restart DD Agent

# TODO: test deploying less nodes than node_count

# - name: Find existing service files
#       find:
#         paths: "{{ service_dir }}"
#         patterns: "{{ service_prefix }}-*.service"
#       register: existing_services

#     - name: Delete extra service files
#       shell: |
#         for service_file in {{ service_dir }}/{{ service_prefix }}-*.service; do
#           node_number=$(echo "$service_file" | grep -oP '(?<=-)\d+(?=\.service)')
#           if [[ "$node_number" -gt {{ node_count }} ]]; then
#             echo "Deleting $service_file"
#             rm "$service_file"
#             systemctl disable "{{ service_prefix }}-$node_number.service"
#           fi
#         done
#         systemctl daemon-reload
#       args:
#         executable: /bin/bash
#       when: existing_services.matched > node_count