---

# - name: Restart all services
#   command: sudo systemctl restart {{ service_prefix }}-*

- name: Restart DD Agent
  ansible.builtin.systemd:
    state: restarted
    name: datadog-agent
    enabled: true