---

- name: Restart DD Agent
  ansible.builtin.systemd:
    state: restarted
    name: datadog-agent
    enabled: true

# needed for Digital Ocean
- name: Restart journald
  ansible.builtin.systemd:
    state: restarted
    name: systemd-journald
    enabled: true