---

- name: Restart all services
  ansible.builtin.systemd:
    name: "avail-light-{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  with_sequence: count="{{ node_count }}"
  listen: "Restart all services"

- name: Restart DD Agent
  ansible.builtin.systemd:
    state: restarted
    name: datadog-agent
    enabled: true