
- name: Include vars for {{ network }} network
  include_vars:
    file: "{{ network }}.yml"

- name: Check if bin exists
  ansible.builtin.stat:
    path: /usr/local/bin/{{ service_prefix }}-{{ bootnode_version }}
  register: bin_installed

- ansible.builtin.include_tasks: binary.yml
  when: not bin_installed.stat.exists

- name: Create config file for {{ group_names[0] }}
  ansible.builtin.template:
    src: "{{ group_names[0] }}.toml"
    dest: "/etc/avail-light/config.toml"
    owner: "{{ avail_user }}"
    group: "{{ avail_user }}"
    mode: 0755

- name: Copy service file
  ansible.builtin.template:
    src: "{{ group_names[0] }}.service"
    dest: "{{ service_dir }}/{{service_prefix}}.service"
    mode: '0755'
  notify:
    - Restart bootnode

# install datadog
- include_role: 
    name: datadog
  vars:
    name: "{{ service_prefix }}"
    version: "{{ bootnode_version }}"