
- name: Download otel collector
  ansible.builtin.get_url:
    url: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v{{ client_version }}/otelcol-contrib_{{ client_version }}_linux_amd64.tar.gz
    dest: /tmp/otelcol-{{ client_version }}.tar.gz
    mode: 0600
    force: true
    timeout: 300

- name: Extract the contrib archive
  unarchive:
    src: "/tmp/otelcol-{{ client_version }}.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true

- name: Rename otelcol-contrib to otelcol
  command: mv /usr/local/bin/otelcol-contrib /usr/local/bin/otel-{{ client_version }}

- name: Clean up otel download file
  file:
    path: "/tmp/otelcol-{{ client_version }}.tar.gz"
    state: absent