hostname: {{ inventory_hostname }}
host_aliases:
  - {{ inventory_hostname }}
api_key: "{{ datadog_api_key }}"
env: "latitude"
logs_enabled: true
forwarder_storage_max_size_in_bytes: 50000000 # 50MB
process_config:
  process_collection:
    enabled: true
network_config:
  enabled: false
systemProbe:
  enabled: enabled

tags:
  - basedn: {{ base_dn }}
  - provisioned_by: ansible