hostname: server-01-lightclient-turing
host_aliases:
  - server-01
api_key: "{{ datadog_api_key }}"
logs_enabled: true
forwarder_storage_max_size_in_bytes: 50000000 # 50MB
process_config:
  process_collection:
    enabled: true
network_config:
  enabled: false
systemProbe:
  enabled: enabled

tags:
  - basedn:"lightclient.{{ network }}"
  - provisioned_by:ansible
  - hosted_on:latitude