logs:
    {%- for num in range(1,node_count +1) %}

    - type: journald
      config_id: avail-light-{{ num }}
      source: avail-light-{{ num }}
      service: {{ client_version }}
      include_units:
          - avail-light-{{ num }}.service
    {%- endfor %}