- hosts: bootnode
  become: true
  gather_facts: true
  vars:
    bootnode_version: v0.0.9
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
  tasks:
    - block:
      - include_role:
          name: bootnode
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure

- hosts: lightnode:fatclient
  become: true
  gather_facts: true
  vars:
    avail_light_version: "{{ lookup('env', 'AVAIL_LIGHT_VERSION') }}"
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
    desired_count: 10
    service_start: "{{ groups[group_names[0]].index(inventory_hostname) * desired_count }}"
    service_end: "{{ (groups[group_names[0]].index(inventory_hostname) + 1) * desired_count }}"
  tasks:
    - block:
      - include_role:
          name: lightclient
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure
  tags:
    - lightclient

- hosts: otel
  become: true
  gather_facts: true
  vars:
    otel_version: 0.97.0
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
  tasks:
    - block:
      - include_role:
          name: collector
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure