- hosts: lightnode:fatclient
  become: true
  gather_facts: true
  vars:
    avail_light_version: v1.9.1
    desired_count: 10
    service_start: "{{ groups[groups.keys() | first].index(inventory_hostname) * desired_count }}"
    service_end: "{{ (groups[groups.keys() | first].index(inventory_hostname) + 1) * desired_count }}"
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
  tasks:
    - block:
      - include_role:
          name: lightclient
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure

- hosts: otel
  become: true
  gather_facts: true
  vars:
    otel_version: 0.97.0
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
  tasks:
    - block:
      - include_role:
          name: collector
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure


# TODO
# Include pre task for datadog key check here instead of duplicating