- hosts: lightnode:fatclient
  become: true
  gather_facts: true
  vars:
    avail_light_version: v1.9.1
    desired_count: 10
    service_start: "{{ groups[groups.keys() | first].index(inventory_hostname) * desired_count }}"
    service_end: "{{ (groups[groups.keys() | first].index(inventory_hostname) + 1) * desired_count }}"
  tasks:
    - block:
      - include_role:
          name: lightclient


- hosts: otel
  become: true
  gather_facts: true
  vars:
    client_version: 0.97.0
  tasks:
    - block:
      - include_role:
          name: collector
# TODO
# Terraform with python to create inventory
# inventory and group vars
# Terraform to deploy dedicated RPC nodes
# Deploy fat clients
# Multiple bootnodes and server mode LCs, DO & latitude
# cloudflare dns for all
# Test reachability and monitors for bootnode and otel
# monitors for systemd services
# datadog monitors on log errors for RPC, bootstraps and dht p2p
# Deploy less nodes and auto cleanup