name: Deploy Lightclients

on:
  push:
    branches: [ "**" ]

jobs:
  hex:
    uses: ./.github/workflows/common.yml
    with:
      network: hex
    secrets:
      datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}