name: Deploy Lightclients

on:
  repository_dispatch:
    types: ["binary_release"]
  
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      bootnode_version:
        description: 'Bootnode version'
        required: false
      avail_light_version:
        description: 'LC version'
        required: false
      network:
        description: 'Network'
        required: false
     
      
jobs:
  hex:
    uses: ./.github/workflows/common.yml
    with:
      network: ${{ inputs.network || 'hex' }}
      avail_light_version: ${{ github.event.client_payload.avail_light_version || inputs.avail_light_version || 'avail-light-client-v1.11.1' }}
      bootnode_version: ${{ github.event.client_payload.bootnode_version || inputs.bootnode_version || 'avail-light-bootstrap-v0.1.4-rc1' }}
    secrets:
      datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
