name: Deploy Lightclients

on:
  repository_dispatch:
    types: ["binary_release"]

  workflow_dispatch:
    inputs:
      bootnode_version:
        description: 'Bootnode version'
        required: true
      avail_light_version:
        description: 'LC version'
        required: true
      network:
        description: 'Network'
        required: true
      
jobs:
  hex:
    uses: ./.github/workflows/common.yml
    with:
      network: ${{ inputs.network || 'hex' }}
      avail_light_version: ${{ github.event.client_payload.avail_light_version || inputs.avail_light_version }}
      bootnode_version: ${{ github.event.client_payload.bootnode_version || inputs.bootnode_version }}
    secrets:
      datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

# TODO: 
# Trigger avail-light release from another repo with version in payload
# include ansible check mode on PRs
# Add branch protection rules
# For Dashboard change Otel datadog source to basedn tag basedn:lightclient.hex
# Monitors
  # system internal service restarts > 50
  # otel & bootnode port connections
  # slack channel to monitor alerts
  # send alerts to pagerduty -> slack (with tagging)
  # create SLO/SLIs

