name: Deploy Lightclients

on:
  push:

jobs:
  ansible:
    runs-on: ubuntu-latest
    env:
      NETWORK: turing
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY}}
      SERVER_COUNT: 20
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: Setup Virtual Environment
      working-directory: ansible
      run: |
        echo "${{ secrets.SSH_KEY }}" >> key && chmod 0600 key && ls -ltr .
        which python
        which ansible
        ssh -i key ubuntu@
    
    - name: view ansible inventory
      working-directory: ansible
      run: ansible-inventory --inventory inventory/${{ env.NETWORK }}.ini --list

    - name: ping all
      working-directory: ansible
      run: ansible all -m ping --inventory inventory/${{ env.NETWORK }}.ini --extra-vars "@${{ env.NETWORK }}-vars.yml" -vvv
  
    - name: run playbook
      working-directory: ansible
      run: ansible-playbook playbook.yml --extra-vars "@${{ env.NETWORK }}-vars.yml"
    
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      if: ${{ failure() }}
      with:
        wait-timeout-minutes: 2
