name: Deploy Lightclients

on:
  repository_dispatch:
    types: ["binary_release"]
    
  push:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the client payload
        env:
          CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: echo "Client Payload: $CLIENT_PAYLOAD"

  hex:
    if: false
    uses: ./.github/workflows/common.yml
    with:
      network: hex
    secrets:
      datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

# TODO: 
# Trigger avail-light release from another repo with version in payload
# include ansible check mode on PRs
# Add branch protection rules
# Monitors
  # system internal service restarts > 50
  # otel & bootnode port connections
  # slack channel to monitor alerts
  # send alerts to pagerduty -> slack (with tagging)
  # create SLO/SLIs
