name: Deploy Lightclients

on:
  push:

env:
  NETWORK: hex
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/deployments/${{ env.NETWORK }}
   
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: configure aws creds
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: terraform init
      run: aws s3 ls && terraform init 

    - name: terraform plan
      run: terraform plan

    - name: terraform apply
      run: terraform apply --auto-approve

    - name: upload ssh key
      uses: actions/upload-artifact@v4
      with:
        name: ansible-files
        path: |
          ansible/${{ env.NETWORK }}_key
          ansible/inventory/${{ env.NETWORK }}.ini

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: ansible

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: download ssh key
      uses: actions/download-artifact@v4
      with:
        name: ansible-files
        path: .

    - name: show ssh key exists
      run: ls -ltr

    - name: view ansible inventory
      run: ansible-inventory --inventory inventory/${{ env.NETWORK }}.ini --list

    - name: ping all
      run: ansible all -m ping --inventory inventory/${{ env.NETWORK }}.ini
  
  #   - name: run playbook
  #     run: ansible-playbook playbook.yml --inventory inventory/${{ env.NETWORK }}.ini
    
  #   - name: Setup upterm session
  #     uses: lhotari/action-upterm@v1
  #     if: ${{ failure() }}
  #     with:
  #       wait-timeout-minutes: 2