name: Deploy Lightclients

on:
  push:

jobs:
  ansible:
    runs-on: ubuntu-latest
    env:
      NETWORK: turing
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY}}
      SERVER_COUNT: 20
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: ssh key setup
      run: |
        echo "${{ secrets.SSH_KEY }}" > key && chmod 600 key && cat key

    - name: view ansible inventory
      working-directory: ansible
      run: ansible-inventory --inventory inventory/${{ env.NETWORK }}.ini --list 

    - name: ping all
      working-directory: ansible
      run: ansible all -m ping --inventory inventory/${{ env.NETWORK }}.ini --extra-vars "@${{ env.NETWORK }}-vars.yml" 
   
    - name: run playbook
      working-directory: ansible
      run: ansible-playbook playbook.yml --extra-vars "@${{ env.NETWORK }}-vars.yml"